### ISSUE TITLE
You have requested a non-existent parameter "babdev_supplier.model.supplier.class".

### ISSUE THREAD

**Issue by Beaudinn** [BabDev/supplier-plugin#1]
Hey,
I'm getting an error
You have requested a non-existent parameter "babdev_supplier.model.supplier.class".
This happens with a clean install, I'm looking in to it but havent found a solution yet

**Comment by czende** [comment]
Hi, you just have to call `php bin/console doctrine:migrations:diff` which will generate migration for you and than just `php bin/console doctrine:migrations:migrate`.

Or not?

**Comment by Beaudinn** [comment]
@czende  no it does not y can't run command because i receive the error then. it looks to me that i need to specify a class that the suppliers are mapped onto.

**Comment by mbabker** [comment]
You did import the config file and enable the plugin (bundle), right?

I don't have a project running this version of the plugin right now so I haven't had much time to check things much further (I am making time to upgrade that project in the next couple of weeks).  Looking purely at the CI build, this shouldn't be a problem with the plugin correctly registered to the app environment.
